### ISSUE TITLE
[FEATURE] Hide "Correct Files" section in the output

### ISSUE THREAD

**Issue by mubinov** [aolenevme/lint-fs#34]
In the output we have several sections: "Incorrect Files" and "Correct Files". First one is useful and necessary, but second one is redundant. I have 10k+ files in my project, and the output looks overloaded.

Suggestions:
- Hide "Correct Files" in the output by default
- Add a debug flag to display this section when needed

**Comment by aolenevme** [comment]
@mubinov, thank you for the open Issue! 🙌🏻

What about `--verbose` CLI flag?

If it is added, we print `Correct Files`. Otherwise the whole `Correct Files` output is skipped.

**Comment by mubinov** [comment]
yes, I think it is a good solution.

**Comment by aolenevme** [comment]
After the discussion with @mubinov, we decided to add `mode` option to the `lint-fs.yaml`.
